# Generated by Django 4.0.4 on 2022-04-29 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cashcalls', '0002_bill_amount_invested_bill_date_bill_fee_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount_invested',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bill',
            name='fee_percentage',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='final_fee',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
