# Generated by Django 4.0.4 on 2022-04-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashcalls', '0003_alter_bill_amount_invested_alter_bill_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount_invested',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='fee_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
